all:
	g++ -std=c++11 -o overcook overcook.cpp -lpthread
	arm-unknown-linux-gnu-g++ -o arm_overcook overcook.cpp -lpthread
window:
	g++ -std=c++11 -o overcook overcook.cpp
pxa:
	arm-unknown-linux-gnu-g++ -o arm_overcook overcook.cpp
clean:
	rm overcook
